#ifndef JELA_H
#define JELA_H

extern void begin_query(tpl_query *q, node *term);
extern void execute_term(tpl_query *q, node *term, unsigned frame_size);
extern void allocate_frame(tpl_query *q);
extern void reallocate_frame(tpl_query *q);
extern void deallocate_frame(tpl_query *q);
extern void prepare_frame(tpl_query *q, unsigned frame_size);
extern int follow(tpl_query *q);
extern int call(tpl_query *q);
extern int match(tpl_query *q);
extern void try_me2(tpl_query *q, int nofollow, int nochoice);
extern int retry_me(tpl_query *q);
extern void trust_me(tpl_query *q);
extern int unify_term(tpl_query *q, node *term1, node *term2, unsigned frame);
extern int query_inline(tpl_query *q);
extern void query_reset(tpl_query *q);

#define try_me(q) try_me2(q, 0, 0)
#define try_me_nofollow(q) try_me2(q, 1, 0)
#define try_me_nochoice(q) try_me2(q, 0, 1)

enum {
	ABORT_NONE,
	ABORT_ABORT,
	ABORT_HALT,
	ABORT_ARGTOOBIG,
	ABORT_MAXENVS,
	ABORT_MAXCHOICES,
	ABORT_OUTOFMEMORY,
	ABORT_TYPEERROR,
	ABORT_MAXDEPTH,
	ABORT_UNDEFINED,
	ABORT_NOTDYNAMIC,
	ABORT_NOTEXISTFUNCTOR,
	ABORT_NOTEXISTPROCESS,
	ABORT_NOTEXISTREMOTE,
	ABORT_NOTEXISTFILE,
	ABORT_NOTCHILD,
	ABORT_NOTCALLABLE,
	ABORT_RESULTOVERFLOW,
	ABORT_CANTCONNECT,
	ABORT_SERVERCANTBIND,
	ABORT_SERVERCANTJOIN,
	ABORT_STREAMCLOSED,
	ABORT_PIDCLOSED,
	ABORT_NOCURRENTPID,
	ABORT_DUPLICATENAME,
	ABORT_INVALIDARGMISSING,
	ABORT_INVALIDARGMAXARITY,
	ABORT_INVALIDARGNOTLESSZERO,
	ABORT_INVALIDARGISVAR,
	ABORT_INVALIDARGNOTVAR,
	ABORT_INVALIDARGNOTNBR,
	ABORT_INVALIDARGNOTATOM,
	ABORT_INVALIDARGNOTLIST,
	ABORT_INVALIDARGNOTSTRUCT,
	ABORT_INVALIDARGNOTTUPLE,
	ABORT_INVALIDOPUNKNOWN,
	ABORT_INVALIDOP,
	ABORT_INVALIDARGNOTCOMPOUND,
	ABORT_INVALIDARGNOTNBRORLIST,
	ABORT_INVALIDARGNOTATOMORINT,
	ABORT_INVALIDARGNOTATOMORLIST,
	ABORT_INVALIDARGNOTATOMORSTRUCT,
	ABORT_INVALIDARGNOTNBRORSTRUCT,
	ABORT_INVALIDARGNOTATOMIC,
	ABORT_INVALIDARGNOTNBRORVAR,
	ABORT_INVALIDARGNOTLISTORVAR,
	ABORT_INVALIDARGNOTATOMORVAR,
	ABORT_INVALIDARGNOTCALLABLE,
	ABORT_INVALIDARGNOTSTRUCTURE,
	ABORT_INVALIDARGNOTVARORLIST,
	ABORT_INVALIDARGNOTVARORNBR,
	ABORT_INVALIDARGNOTVARORATOM,
	ABORT_INVALIDARGNOTVARORCALLABLE,
	ABORT_INVALIDARGNOTINT,
	ABORT_INVALIDARGNOTPTR,
	ABORT_INVALIDARGNOTFLOAT,
	ABORT_INVALIDARGDIVIDEBYZERO,
	ABORT_INVALIDARGNOTGROUNDED,
	ABORT_INVALIDARGNOTSTREAM,
	ABORT_INVALIDARGNOTFILE,
	ABORT_INVALIDARGNOTSOCKET,
	ABORT_INVALIDARGNOTWEBSOCKET,
	ABORT_INVALIDARGNOTBLOB,
	ABORT_INVALIDARGNOTPID,
	ABORT_INVALIDARGNOTKVSTORE,
	ABORT_END
};

#endif
